name: main

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    env:
      # github.com/wasm-bindgen/wasm-bindgen/pull/4717
      RUSTFLAGS: -Dwarnings -Ctarget-feature=+simd128,+atomics,+bulk-memory,+mutable-globals -Clink-args=--shared-memory -Clink-args=--max-memory=1073741824 -Clink-args=--import-memory -Clink-args=--export=__wasm_init_tls -Clink-args=--export=__tls_size -Clink-args=--export=__tls_align -Clink-args=--export=__tls_base
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: supplypike/setup-bin@v4
        with:
          uri: "https://github.com/WebAssembly/binaryen/releases/download/version_124/binaryen-version_124-aarch64-linux.tar.gz"
          name: "wasm-opt"
          version: "124"
          subPath: "binaryen-version_124/bin"
      - uses: taiki-e/install-action@v2
        with:
          tool: wasm-bindgen@0.2.104
      - run: |
          rustup target add wasm32-unknown-unknown
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Build rapier2d
        run: |
          cd rapier2d
          cargo build --release --verbose --target wasm32-unknown-unknown -Z build-std=panic_abort,std
          WASM_BINDGEN_EXPERIMENTAL_SYMBOL_DISPOSE=1 wasm-bindgen ../target/wasm32-unknown-unknown/release/rapier_wasm2d.wasm --out-dir ./pkg --typescript --target web
          wasm-opt ./pkg/rapier_wasm2d_bg.wasm -o ./pkg/rapier_wasm2d_bg.wasm -Oz --dce --enable-simd --enable-bulk-memory --enable-nontrapping-float-to-int --enable-threads --enable-mutable-globals
          ./build_typescript.sh
          pnpm tsc
      - uses: actions/upload-artifact@v4
        with:
          name: pkg
          path: |
            rapier2d/pkg
          compression-level: 9
